import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.scss';

import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import type { ThemeConfig } from 'antd';
import variables from '../styles/variables.module.scss';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const config: ThemeConfig = {
  // // Use dark algorithm
  // algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary: variables.primaryColor,
    colorBgContainer: variables.backgroundButtonColor,
  },
  components: {
    Button: {
      fontWeight: 600,
      borderRadius: 4,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AntdRegistry>
          <ConfigProvider theme={config}>{children}</ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
